
- debug:
    msg: "vcn_id is not defined. Please pass in vcn OCID."
  when: vcn_id is not defined 

- name: Delete vcn
  oci_network_vcn:
    vcn_id: "{{ vcn_id }}"
    state: absent
  when: vcn_id is defined

