
# Check for required variables
  


# Create Networking

- name: Create VCN
  include_tasks: vcn.yml

- name: Add Networking for Public Subnet
  include_tasks: public_subnet_networking.yml

- name: Add Networking for Private Subnet
  include_tasks: private_subnet_networking.yml