
# Check for required variables
  
- block:
  - name: Check compartment_id variable
    debug:
      msg: "compartment_id is not defined. Please pass in compartment OCID."
  - meta: end_host
  when: compartment_id is not defined

# Create Networking

- name: Create VCN
  oci_network_vcn:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ network_tag }}VCN"
    cidr_block: "{{ vcn_cidr_block }}"
    dns_label: "{{ network_tag }}VCN"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    vcn_id: "{{ result.vcn.id }}"
    default_route_table_id: "{{ result.vcn.default_route_table_id }}"
    default_security_list_id: "{{ result.vcn.default_security_list_id }}"

- name: Add Networking for Public Subnet
  include_tasks: public_subnet_networking.yml

- name: Add Networking for Private Subnet
  include_tasks: private_subnet_networking.yml