

# Create Networking

- name: Create VCN
  include_tasks: vcn.yml

# - name: Add Networking for Backup Subnet
#   include_tasks: backup_subnet.yml

# - name: Add Networking for Client Subnet
#   include_tasks: client_subnet.yml