

# Create Networking

- name: Create VCN
  include_tasks: create_vcn.yml

- name: List Oracle Services
  include_tasks: network_service_discovery.yml

- name: Add Networking for Backup Subnet
  include_tasks: create_backup_subnet.yml
  
- name: Add Networking for Client Subnet
  include_tasks: create_client_subnet.yml