
# Drop All Routes from Route Tables

- name: Update default route table to drop any gateways
  when: lookup('vars', network_tag + '_default_route_table_id', default="") != ""
  oci_network_route_table:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_default_route_table_id') }}"
    route_rules: []

- name: Update backup route table to drop any gateways
  when: lookup('vars', network_tag + '_backup_route_table_id', default="") != ""
  oci_network_route_table:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_backup_route_table_id') }}"
    route_rules: []

- name: Update client route table to drop any gateways
  when: lookup('vars', network_tag + '_client_route_table_id', default="") != ""
  oci_network_route_table:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_client_route_table_id') }}"
    route_rules: []

# Delete Remote Peering Components

- name: Delete remote peering connection
  when: lookup('vars', network_tag + '_rpc_id', default="") != ""
  oci_network_remote_peering_connection:
    region: "{{ region }}"
    remote_peering_connection_id: "{{ lookup('vars', network_tag + '_rpc_id') }}"
    state: absent

- name: Delete drg_attachment
  when: lookup('vars', network_tag + '_drg_attachment_id', default="") != ""
  oci_network_drg_attachment:
    region: "{{ region }}"
    drg_attachment_id: "{{ lookup('vars', network_tag + '_drg_attachment_id') }}"
    state: absent

- name: Delete drg
  when: lookup('vars', network_tag + '_drg_id', default="") != ""
  oci_network_drg: 
    region: "{{ region }}"
    drg_id: "{{ lookup('vars', network_tag + '_drg_id') }}"
    state: absent

# Terminate Gateways

- name: Delete service gateway
  when: lookup('vars', network_tag + '_service_gateway_id', default="") != ""
  oci_network_service_gateway:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_service_gateway_id') }}"
    state: absent

- name: Delete nat gateway
  when: lookup('vars', network_tag + '_nat_gateway_id', default="") != ""
  oci_network_nat_gateway:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_nat_gateway_id') }}"
    state: absent

- name: Delete internet gateway
  when: lookup('vars', network_tag + '_internet_gateway_id', default="") != ""
  oci_network_internet_gateway:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_internet_gateway_id') }}"
    state: absent

# Terminate Backup Networking Components

- name: Delete private subnet
  when: lookup('vars', network_tag + '_private_subnet_id', default="") != ""
  oci_network_subnet:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_private_subnet_id') }}"
    state: absent

- name: Delete custom route table 
  when: lookup('vars', network_tag + '_private_route_table_id', default="") != ""
  oci_network_route_table:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_private_route_table_id') }}"
    state: absent

- name: Delete custom security list 
  when: lookup('vars', network_tag + '_private_security_list_id', default="") != ""
  oci_network_security_list:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_private_security_list_id') }}"
    state: absent


# Delete Public Networking Components

- name: Delete public subnet
  when: lookup('vars', network_tag + '_public_subnet_id', default="") != ""
  oci_network_subnet:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_public_subnet_id') }}"
    state: absent

- name: Delete db security list 
  when: lookup('vars', network_tag + '_db_security_list_id', default="") != ""
  oci_network_security_list:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_db_security_list_id') }}"
    state: absent

# Delete VCN 

- name: Delete the VCN
  when: lookup('vars', network_tag + '_vcn_id', default="") != ""
  oci_network_vcn:
    region: "{{ region }}"
    id: "{{ lookup('vars', network_tag + '_vcn_id') }}"
    state: absent