
# Check for required variables.
  
- block: 
  - name: "Check VCN variables."
    debug:
      msg: "VCN values not defined. Please run vcn_subnets.yml and pass in vcn, route table, and security list OCIDs."
  - meta: end_host
  when: vcn_id is not defined or default_route_table_id is not defined or default_security_list_id is not defined

# Create Networking for Private Subnet

- name: Create nat gateway
  oci_network_nat_gateway:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    display_name: "{{ network_tag }}NG"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    nat_gateway_id: "{{ result.nat_gateway.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_nat_gateway_id: {{ nat_gateway_id }}"

- name: List Oracle services
  oci_network_service_facts:
    region: "{{ region }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    oci_iad_object_storage_id: "{{ result.services[0].id }}"
    all_iad_services_id: "{{ result.services[1].id }}"
  
- name: Create service gateway
  oci_network_service_gateway:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    display_name: "{{ network_tag }}SG"
    services:
    - service_id: "{{ all_iad_services_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    service_gateway_id: "{{ result.service_gateway.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_service_gateway_id: {{ service_gateway_id }}"
    
- name: Create custom route table
  oci_network_route_table:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    display_name: "{{ network_tag }}PrivateRT"
    route_rules:
    - destination_type: CIDR_BLOCK
      destination: "0.0.0.0/0"
      network_entity_id: "{{ nat_gateway_id }}"
    - destination_type: SERVICE_CIDR_BLOCK
      destination: "all-iad-services-in-oracle-services-network"
      network_entity_id: "{{ service_gateway_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    private_route_table_id: "{{ result.route_table.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_private_route_table_id: {{ private_route_table_id }}"
    
- name: Create custom security list
  oci_network_security_list:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    display_name: "{{ network_tag }}PrivateSL"
    ingress_security_rules:
    - protocol: "6"
      source: "{{ vcn_cidr_block }}"
      tcp_options:
        destination_port_range:
          min: "22"
          max: "22"
    - protocol: "1"
      source: "0.0.0.0/0"
      icmp_options:
        type: "3"
        code: "4"
    - protocol: "1"
      source: "{{ vcn_cidr_block }}"
      icmp_options:
        type: "3"
    egress_security_rules:
    - protocol: "all"
      destination: "0.0.0.0/0"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    private_security_list_id: "{{ result.security_list.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_private_security_list_id: {{ private_security_list_id }}"

- name: Create private subnet with custom route table and security list
  oci_network_subnet:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    cidr_block: "{{ private_subnet_cidr_block }}"
    display_name: "{{ network_tag }}PrivateSubnet"
    prohibit_public_ip_on_vnic: "true"
    dns_label: "{{ network_tag }}Priv"
    route_table_id: "{{ private_route_table_id }}"
    security_list_ids: 
    - "{{ private_security_list_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    private_subnet_id: "{{ result.subnet.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_private_subnet_id: {{ private_subnet_id }}"
      
      
      
      
     