
# Check for required variables.

- block: 
  - name: "Check VCN variables."
    debug:
      msg: "VCN values not defined. Please run vcn_subnets.yml and pass in vcn, route table, and security list OCIDs."
  - meta: end_host
  when: vcn_id is not defined or default_route_table_id is not defined or default_security_list_id is not defined

# Create Networking for Public Subnet

- name: Create internet gateway
  oci_network_internet_gateway:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    display_name: "{{ network_tag }}IG"
    is_enabled: true
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    internet_gateway_id: "{{ result.internet_gateway.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_internet_gateway_id: {{ internet_gateway_id }}"

- name: Add internet gateway route to default route table
  oci_network_route_table:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    id: "{{ default_route_table_id }}"
    route_rules:
    - destination_type: CIDR_BLOCK
      destination: "0.0.0.0/0"
      network_entity_id: "{{ internet_gateway_id }}"
  register: result
- debug:
    msg: "{{ result }}"

- name: Create public subnet with default values for route table, security list, & DHCP options
  oci_network_subnet:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    cidr_block: "{{ public_subnet_cidr_block }}"
    display_name: "{{ network_tag }}PublicSubnet"
    prohibit_public_ip_on_vnic: "false"
    dns_label: "{{ network_tag }}Pub"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    public_subnet_id: "{{ result.subnet.id }}"
- lineinfile:
    path: ./vars/networking_ocids.yml
    line: "{{ network_tag }}_public_subnet_id: {{ public_subnet_id }}"
      