# DB specific requirements
# - both security lists should allow incoming connections to port 1521 (can use other VCNs cidr or just 0.0.0.0)
# Remote Peering

# Create Standby Region Basic Networking

- name: Create VCN (Standby)
  include_tasks: vcn.yml
  vars:
    region: "{{ standby_region }}"
    network_tag: "{{ standby_network_tag }}"
    vcn_cidr_block: "{{ standby_vcn_cidr_block }}"  

- name: Create Client Security List for Standby
  oci_network_security_list:
    region: "{{ standby_region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    display_name: "{{ standby_network_tag }}ClientSL"
    ingress_security_rules:
    - protocol: "6"
      source: "{{ vcn_cidr_block }}"
      tcp_options:
        destination_port_range:
          min: "1521"
          max: "1521"
    egress_security_rules:
    - protocol: "6"
      destination: "{{ vcn_cidr_block }}"
      tcp_options:
        destination_port_range:
          min: "1521"
          max: "1521"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    client_security_list_id: "{{ result.security_list.id }}"

- name: Create public subnet with default values for route table, security list, & DHCP options
  oci_network_subnet:
    region: "{{ standby_region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    cidr_block: "{{ standby_client_subnet_cidr_block }}"
    display_name: "{{ standby_network_tag }}CS"
    prohibit_public_ip_on_vnic: "false"
    dns_label: "{{ standby_network_tag }}Pub"
    security_list_ids:
    - "{{ default_security_list_id }}"
    - "{{ client_security_list_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    client_subnet_id: "{{ result.subnet.id }}"
     

# Create Standby Region DRG and RPC

- name: Create standby drg
  oci_network_drg:
    region: "{{ standby_region }}"
    display_name: "{{ standby_network_tag }}DRG"
    compartment_id: "{{ compartment_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    standby_drg_id: "{{ result.drg.id }}"

- name: Create standby drg_attachment 
  oci_network_drg_attachment:
    region: "{{ standby_region }}"
    drg_id: "{{ standby_drg_id }}"
    display_name: "{{ standby_network_tag }}DRGAttachment"
    compartment_id: "{{ compartment_id }}"
    network_details:
      type: VCN
      id: "{{ vcn_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    standby_drg_attachment_id: "{{ result.drg_attachment.id }}"

- name: Add drg route to standby default route table
  oci_network_route_table:
    region: "{{ standby_region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    id: "{{ default_route_table_id }}"
    route_rules:
    - destination_type: CIDR_BLOCK
      destination: "{{ vcn_cidr_block }}"
      network_entity_id: "{{ standby_drg_id }}"
  register: result
- debug:
    msg: "{{ result }}"

- name: Create standby remote peering connection
  oci_network_remote_peering_connection:
    region: "{{ standby_region }}"
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ standby_network_tag }}RPC"
    drg_id: "{{ standby_drg_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    standby_rpc_id: "{{ result.remote_peering_connection.id }}" 

# Create Primary Region DRG and RPC

- name: Primary VCN OCID
  include_tasks: vcn_discovery.yml

- name: Create prod drg
  oci_network_drg:
    region: "{{ region }}"
    display_name: "{{ network_tag }}DRG"
    compartment_id: "{{ compartment_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    prod_drg_id: "{{ result.drg.id }}"

- name: Create prod drg_attachment 
  oci_network_drg_attachment:
    region: "{{ region }}"
    drg_id: "{{ prod_drg_id }}"
    display_name: "{{ network_tag }}DRGAttachment"
    compartment_id: "{{ compartment_id }}"
    network_details:
      type: VCN
      id: "{{ primary_vcn_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    prod_drg_attachment_id: "{{ result.drg_attachment.id }}"

# Add DRG to Route Table

- name: Add drg route to client route table when subnet is public
  when: primary_internet_gateway_id is defined
  oci_network_route_table:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ primary_vcn_id }}"
    id: "{{ primary_client_route_table_id }}"
    route_rules:
    - destination_type: CIDR_BLOCK
      destination: "{{ standby_vcn_cidr_block }}"
      network_entity_id: "{{ prod_drg_id }}"
    - destination_type: CIDR_BLOCK
      destination: "0.0.0.0/0"
      network_entity_id: "{{ primary_internet_gateway_id }}"
  register: result
- debug:
    msg: "{{ result }}"

- name: Add drg route to client route table when subnet is private
  when: primary_nat_gateway_id is defined
  oci_network_route_table:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    vcn_id: "{{ primary_vcn_id }}"
    id: "{{ primary_client_route_table_id }}"
    route_rules:
    - destination_type: CIDR_BLOCK
      destination: "{{ standby_vcn_cidr_block }}"
      network_entity_id: "{{ prod_drg_id }}"
    - destination_type: CIDR_BLOCK
      destination: "0.0.0.0/0"
      network_entity_id: "{{ nat_gateway_id }}"
    - destination_type: SERVICE_CIDR_BLOCK
      destination: "all-iad-services-in-oracle-services-network"
      network_entity_id: "{{ service_gateway_id }}"
  register: result
- debug:
    msg: "{{ result }}"

# Continue creation remote peering connection

- name: Create prod remote peering connection
  oci_network_remote_peering_connection:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ network_tag }}RPC"
    drg_id: "{{ prod_drg_id }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    prod_rpc_id: "{{ result.remote_peering_connection.id }}"

- name: Perform action connect on remote_peering_connection
  oci_network_remote_peering_connection_actions:
    region: "{{ standby_region }}"
    remote_peering_connection_id: "{{ standby_rpc_id }}"
    peer_id: "{{ prod_rpc_id }}"
    peer_region_name: "{{ region }}"
    action: connect
  register: result
- debug:
    msg: "{{ result }}"





