
- name: Subnet discovery
  oci_network_subnet_facts:
    compartment_id: '{{ compartment_id }}'
    display_name: '{{ subnet_name }}'
    vcn_id: '{{ vcn_id }}'
  register: subnet_discovery_result
- debug:
    msg: '{{ subnet_discovery_result }}'
- set_fact: 
    subnet_id: '{{ subnet_discovery_result.subnets[0].id }}'
    subnet_route_table_id: '{{ subnet_discovery_result.subnets[0].route_table_id }}'
    subnet_security_list_ids: '{{ subnet_discovery_result.subnets[0].security_list_ids }}'
  when: subnet_discovery_result.subnets|length > 0 