
- name: 'Check compartment_id variable.'
  assert:
    that:
      - compartment_id is defined
    fail_msg: 'compartment_id is not defined. Please pass in compartment OCID.'

- name: Create VCN
  oci_network_vcn:
    cidr_block: '{{ vcn_cidr_block }}'
    compartment_id: '{{ compartment_id }}'
    defined_tags: '{{ vcn_defined_tags }}'
    display_name: '{{ workload_tag }}VCN'
    dns_label: '{{ workload_tag }}vcn'
    freeform_tags: '{{ vcn_freeform_tags }}'
    is_ipv6_enabled: '{{ is_ipv6_enabled }}'
    key_by: ['display_name']
  register: vcn_create_result
- debug:
    msg: '{{ vcn_create_result }}'
- set_fact:
    vcn_id: '{{ vcn_create_result.vcn.id }}'
    default_route_table_id: '{{ vcn_create_result.vcn.default_route_table_id }}'
    default_security_list_id: '{{ vcn_create_result.vcn.default_security_list_id }}'