
- name: 'Check compartment_id variable.'
  assert:
    that:
      - compartment_id is defined
    fail_msg: 'compartment_id is not defined. Please pass in compartment OCID.'

- name: VCN discovery
  include_tasks: vcn_discovery.yml

- assert: { that: vcn_id is not defined }

- name: Create VCN
  oci_network_vcn:
    compartment_id: '{{ compartment_id }}'
    display_name: '{{ workload_tag }}VCN'
    cidr_block: '{{ vcn_cidr_block }}'
    dns_label: '{{ workload_tag }}VCN'
  register: result
- debug:
    msg: '{{ result }}'
- set_fact:
    vcn_id: '{{ result.vcn.id }}'
    default_route_table_id: '{{ result.vcn.default_route_table_id }}'
    default_security_list_id: '{{ result.vcn.default_security_list_id }}'