
- name: List vcns
  oci_network_vcn_facts:
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ network_tag }}VCN"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact: 
    vcn_id: "{{ result.vcns[0].id}}"
    default_route_table_id: "{{ result.vcns[0].default_route_table_id}}"
    default_security_list_id: "{{ result.vcns[0].default_security_list_id}}"
  when: result.vcns|length > 0 