
- name: 'Discover VM Cluster for DB Home {{ workload_tag }}{{ db_home_name }}'
  when: vm_cluster_id is not defined
  include_role:
    name: exacs_vm_cluster
    tasks_from: exacs_vm_cluster_discovery.yml
- assert: { that: vm_cluster_id is defined }

- name: 'Create db home with name {{ workload_tag }}{{ db_home_name }}'
  oci_database_db_home:
    compartment_id: '{{ compartment_id }}'
    db_version: '{{ db_version }}'
    display_name: '{{ workload_tag }}{{ db_home_name }}'
    key_by: ['vm_cluster_id', 'display_name']
    source: 'VM_CLUSTER_NEW'
    vm_cluster_id: '{{ vm_cluster_id }}'
  register: db_home_create_result
- debug:
    msg: '{{ db_home_create_result }}'
- set_fact:
    db_home_id: '{{ db_home_create_result.db_home.id }}'