- assert: { that: exadata_type is defined }

- name: 'Discover VM Cluster for DB Home {{ workload_tag }}{{ db_home_name }}'
  when: vm_cluster_id is not defined
  include_role:
    name: '{{ exadata_type }}_vm_cluster'
    tasks_from: '{{ exadata_type }}_vm_cluster_discovery.yml'
- name: 'Assert that vm_cluster_id is defined'
  assert: { that: vm_cluster_id is defined }

# Source is VM_CLUSTER_NEW (default)

- name: 'Create db home with name {{ workload_tag }}{{ db_home_name }}'
  oci_database_db_home:
    compartment_id: '{{ compartment_id }}'
    database_software_image_id: '{{ database_software_image_id }}'
    defined_tags: '{{ db_home_defined_tags }}'
    db_version: '{{ db_version }}'
    display_name: '{{ workload_tag }}{{ db_home_name }}'
    freeform_tags: '{{ db_home_freeform_tags }}'
    key_by: ['vm_cluster_id', 'display_name']
    kms_key_id: '{{ kms_key_id }}'
    kms_key_version_id: '{{ kms_key_version_id }}'
    source: '{{ db_home_source }}'
    vm_cluster_id: '{{ vm_cluster_id }}'
  register: 'db_home_create_result'
- debug:
    msg: '{{ db_home_create_result }}'
- set_fact:
    db_home_id: '{{ db_home_create_result.db_home.id }}'