
- name: Check for existing DB Home
  include_tasks: db_home_discovery.yml

- assert: { that: vm_cluster_id is defined and db_home_id is not defined }

- name: Create db home
  oci_database_db_home:
    compartment_id: '{{ compartment_id }}'
    source: 'VM_CLUSTER_NEW'
    vm_cluster_id: '{{ vm_cluster_id }}'
    display_name: '{{ workload_tag }}{{ db_home_name }}'
    db_version: '{{ db_version }}'
  register: result
- debug:
    msg: '{{ result }}'
- set_fact:
    db_home_id: '{{ result.db_home.id }}'