- name: 'Discover VM Cluster for DB Home {{ workload_tag }}{{ db_home_name }}'
  when: vm_cluster_id is not defined and exadata_type is defined
  include_role:
    name: '{{ exadata_type }}_vm_cluster'
    tasks_from: '{{ exadata_type }}_vm_cluster_discovery.yml'
- assert: { that: vm_cluster_id is defined }

- name: 'Discover DB Home {{ workload_tag }}{{ db_home_name }}'
  oci_database_db_home_facts:
    compartment_id: '{{ compartment_id }}'
    display_name: '{{ workload_tag }}{{ db_home_name }}'
    vm_cluster_id: '{{ vm_cluster_id }}'
  register: 'db_home_discovery_result'
- debug:
    msg: '{{ db_home_discovery_result }}'
- set_fact: 
    db_home_id: '{{ db_home_discovery_result.db_homes[0].id }}'
    db_home_lifecycle_state: '{{ db_home_discovery_result.db_homes[0].lifecycle_state }}'
    oracle_home: '{{ db_home_discovery_result.db_homes[0].db_home_location }}'
  when: db_home_discovery_result.db_homes|length == 1 