- name: Discover VM Cluster for DB Home '{{ workload_tag }}{{ db_home_name }}'
  when: vm_cluster_id is not defined
  include_role:
    name: database_home
    tasks_from: db_home_discovery.yml
- assert: { that: vm_cluster_id is defined }

- name: Discover DB Home '{{ workload_tag }}{{ db_home_name }}'
  oci_database_db_home_facts:
    compartment_id: '{{ compartment_id }}'
    display_name: '{{ workload_tag }}{{ db_home_name }}'
  register: result
- debug:
    msg: '{{ result }}'
- set_fact: 
    db_home_id: '{{ result.db_homes[0].id}}'
  when: result.db_homes|length > 0 