
- name: Check ExaCC VM Cluster Lifecycle State
  when: exadata_type is defined and exadata_type == 'exacc'
  include_role:
    name: exacc_vm_cluster
    tasks_from: exacc_vm_cluster_discovery.yml

- name: Check ExaCC VM Cluster Lifecycle State
  when: exadata_type is defined and exadata_type == 'exacs'
  include_role:
    name: exacs_vm_cluster
    tasks_from: exacs_vm_cluster_discovery.yml

- name: Create DB Home 
  include_tasks: db_create_home.yml
  when: vm_cluster_lifecycle_state is defined and vm_cluster_lifecycle_state == 'AVAILABLE'
    
    