
- assert: { that: exadata_type is defined }

- name: 'Discover VM Cluster for DB Home {{ workload_tag }}{{ db_home_name }}'
  when: vm_cluster_id is not defined
  include_role:
    name: '{{ exadata_type }}_vm_cluster'
    tasks_from: '{{ exadata_type }}_vm_cluster_discovery.yml'

# Create Database Home

- name: 'Create DB Home' 
  include_tasks: 'db_create_home.yml'
    
    