
# Playbook add_pdb.yml adds a PDB to the designated database.

# TO DO!!

- hosts: "server"
  become: true
  become_user: oracle
  gather_facts: no
  # vars:
  #   sys_system_pw: "WelcomeDB12##"
  
  tasks:
  # - name: "creating pdb"
  #   pdb:
  #     oracle_home: "/u01/app/oracle/product/19.0.0.0/dbhome_1"
  #     dbname: "PR2_iad1fh"
  #     pdbname: "PDB2"
  #     state: present
  #     password: "WelcomeDB12##"
    
    # - name: "srvctl config"
    #   shell: |
    #     /u01/app/19.0.0.0/grid/bin/srvctl config database -v
    #   args:
    #     chdir: /home/grid
    #   register: result
    # - debug:
    #     msg: "{{ result }}"
    
    - copy:
        src: ./files/show_pdbs.sql
        dest: /home/oracle
      

    - name: "log_on"
      shell: echo exit |
        $ORACLE_HOME/bin/sqlplus -s / as sysdba @/home/oracle/show_pdbs.sql
      environment:
        ORACLE_HOME: '/u01/app/oracle/product/19.0.0.0/dbhome_1'
        ORACLE_SID: 'PR2'
        ORACLE_UNIQUE_NAME: 'PR2_iad1fh'
      register: result
    - debug:
        msg: "{{ result }}"
    
        