
# Playbook add_pdb.yml adds a PDB to the designated database.

# TO DO!!

- hosts: "server"
  # gather_facts: no
  # become: yes
  # become_user: grid
  # vars:
  #   sys_system_pw: "WelcomeDB12##"
  
  tasks:
  # - name: "creating pdb"
  #   pdb:
  #     oracle_home: "/u01/app/oracle/product/19.0.0.0/dbhome_1"
  #     dbname: "PR2_iad1fh"
  #     pdbname: "PDB2"
  #     state: present
  #     password: "WelcomeDB12##"
    
    # - name: "become grid"
    #   become: yes
    #   become_user: grid
    #   shell: "/u01/app/19.0.0.0/grid/bin/srvctl config database -v"
    #   register: result
    # - debug:
    #     msg: "{{ result }}"
  
    - name: "become grid"
      become: yes
      # become_exe: "sudo su -"
      # become_method: sudo
      become_user: grid
      # pipelining: true
      command: "srvctl config database -v"
      args:
        chdir: /home/grid       
      register: result
    - debug:
        msg: "{{ result }}"
    
        