
# Playbook add_pdb.yml adds a PDB to the designated database.

# TO DO!!

- hosts: "server"
  # gather_facts: no
  become: yes
  # become_user: oracle
  
  tasks:
  # - name: "creating pdb"
  #   pdb:
  #     oracle_home: "/u01/app/oracle/product/19.0.0.0/dbhome_1"
  #     dbname: "PR2_iad1fh"
  #     pdbname: "PDB2"
  #     state: present
  #     password: "WelcomeDB12##"
    
    - name: "become grid"
      # gather_facts: no
      # shell: "srvctl config database -v"
      command: "mkdir test"
      register: result
    - debug:
        msg: "{{ result }}"
    
    - name: "become grid"
      # gather_facts: no
      # shell: "srvctl config database -v"
      shell: "ls"
      register: result
    - debug:
        msg: "{{ result }}"
        