- hosts: '{{ exa }}client01.heb.com'
  gather_facts: no
  become: yes
  become_user: oracle
  vars:
    sys_system_pw: "{{ vault[env_type.lower()].sys_system_pw }}"
  tasks:
  - name: "creating pdb {{ pdb_name }}"
    pdb:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}"
      state: present
      password: "{{ sys_system_pw }}"
  
  - name: "enable tde for {{ pdb_name }}"
    tde_pdb:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}"
      state: present
      password: "{{ sys_system_pw }}"
    when: tde
  
  - name: create data tablespace
    tablespace:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}"
      initial_size: 1G
      next_size: 1G
      max_size: 100G
      tablespace_name: data
      default_tablespace: yes
      encrypted: "{{ tde }}"
      state: present
 
  - name: modify temp tablespace
    tablespace:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}"
      tablespace_name: temp
      initial_size: 1G
      next_size: 1G
      max_size: 32G
  
  - name: "configure database vault for {{ pdb_name }}"
    dbv_pdb:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}"
      password: "{{ sys_system_pw }}"
      log_dir: "{{ work_dir }}"
      state: disabled

  - name: create custom profiles
    custom_profiles:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}" 

  - name: create services
    srvctl_service:
      oracle_home: "{{ oracle_home }}"
      dbname: "{{ db_unique_name }}"
      pdbname: "{{ pdb_name }}" 
      service_name: "{{ pdb_name }}_rw"
      state: present
