
- name: Dataguard
  hosts: localhost
  
  tasks:
    
    - name: Create Remote Peering
      include_role:
        name: networking
        tasks_from: remote_peering.yml
      vars:
        compartment_id: "ocid1.compartment.oc1..aaaaaaaab3yw6vwv6zafelbx6zvhuszn5iaoesrwxkh6d645arl266w4aofq"

      
    