
# Playbook enable_dataguard.yml creates a data guard standby database by setting up remote peering through the networking role, 
# setting up the standby exadata and database, and then enabling dataguard. 


- name: 'Dataguard'
  hosts: 'localhost'

  tasks:

    - include_vars:
        dir: './vars'
        files_matching: '{{ vars_file }}'

    - name: 'Create Remote Peering'
      include_role:
        name: 'networking'
        tasks_from: 'remote_peering.yml'
       
    # - name: 'Create Exadata Infrastructure for ExaCS'
    #   include_role:
    #     name: 'exadata_infra'
    
    # - name: 'Create VM Cluster for ExaCS'
    #   include_role:
    #     name: 'exadata_vm_cluster'
    
    # - name: 'Create Database Home for ExaCS'
    #   include_role:
    #     name: 'database_home'

    # - name: 'Create Database for ExaCS'
    #   include_role:
    #     name: 'database'

    # - name: 'Enable DataGuard'
    #   include_role:
    #     name: 'database'
    #     tasks_from: 'dataguard.yml'



      
    