
# Playbook enable_dataguard.yml creates a data guard standby database by setting up remote peering through the networking role, 
# setting up the standby exadata and database, and then enabling dataguard. 

# To ensure you are creating your environment with the correct values, please check the defaults/main.yml file within each role or pass in 
# the desired value under vars for each task. These variables will take precedence over the defaults.

# Run this playbook with the following command in order to set the variable db_admin_password:

#     ansible-playbook dataguard_setup.yml --extra-vars "db_admin_password=<db_admin_password>"


- name: Dataguard
  hosts: localhost

  vars:
    compartment_id: "ocid1.compartment.oc1..aaaaaaaab3yw6vwv6zafelbx6zvhuszn5iaoesrwxkh6d645arl266w4aofq"

  tasks:

    - name: Create Remote Peering
      include_role:
        name: networking
        tasks_from: remote_peering.yml
       
    # - name: Create Exadata Infrastructure for ExaCS
    #   include_role:
    #     name: exadata_infra
    
    # - name: Create VM Cluster for ExaCS
    #   include_role:
    #     name: exadata_vm_cluster
    
    # - name: Create Database Home for ExaCS
    #   include_role:
    #     name: database_home_creation
    #   vars:
    #     vm_cluster_id: "ocid1.dbsystem.oc1.phx.abyhqljsocyxodibkxdqsnkx3z5gu2lvjczhseei6ju3knvmr3w2mi2yz56a" 
    #     compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" 
    
    # - name: Create Database for ExaCS
    #   include_role:
    #     name: database_creation
    #   vars:
    #     compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" 
    #     db_home_id: "ocid1.dbhome.oc1.phx.abyhqljsctnqkpksjxbiu7abdl2mujajupge7k3d2snk3whjczanpzjxjm6a"

    # - name: Enable DataGuard
    #   include_role:
    #     name: database_creation
    #     tasks_from: dataguard.yml
    #   vars:
    #     primary_database_id: ""
    #     standby_availability_domain: "rLid:PHX-AD-1"
    #     standby_hostname: "drdb2"
    #     standby_subnet_id: ""


      
    