
- name: 'Database Set-Up'
  hosts: 'localhost'
    
  tasks:

    - include_vars:
        dir: './vars'
        files_matching: '{{ vars_file }}'

    - name: 'Create Database Backup'
      include_role:
        name: 'database_backups'