
- name: 'Database Backup'
  hosts: 'localhost'
    
  tasks:

    - include_vars:
        file: './vars/{{ item }}'
      loop: '{{ vars_list }}'

    - name: 'Create Database Backup'
      include_role:
        name: 'database_backups'