
- name: 'Database Home Set-Up'
  hosts: 'localhost'
    
  tasks:

    - include_vars:
        dir: './vars'
        files_matching: '{{ vars_file }}'
    
    - name: 'Create Database Home for ExaCS'
      include_role:
        name: 'database_home'