
- name: 'Database Home Set-Up'
  hosts: 'localhost'
    
  tasks:

    - include_vars:
        file: './vars/{{ item }}'
      loop: '{{ vars_list }}'
    
    - name: 'Create Database Home for ExaCS'
      include_role:
        name: 'database_home'