
# Playbook db_teardown.yml terminates several databases and db homes by looping through a list of OCIDs. 

- name: DB Teardown For Testing
  hosts: localhost
  
  vars:
      exadata_type: exacc
      workload_prefix: t1
      
      vm_cluster_id: "ocid1.vmcluster.oc1.iad.abuwcljrzcdgple4uivfe7gnqoq5gbu6oiljqzk3jl5p7ue3as2wzibuqwwq" 
      compartment_id: "ocid1.compartment.oc1..aaaaaaaazeugz2noyvztfhzqzrk7dwjhvu54v4z7av5tloeryz5pkq6oxgrq" 
  
  tasks:
    
    - name: Delete DBs
      include_role:
        name: database_creation
        tasks_from: db_delete_database.yml

    - name: Delete DB Homes
      include_role:
        name: database_home_creation
        tasks_from: db_delete_home.yml
    