
# Playbook enable_dataguard.yml creates a data guard standby database by setting up remote peering through the networking role, 
# setting up the standby exadata and database, and then enabling dataguard. 

# To ensure you are creating your environment with the correct values, please check the defaults/main.yml file within each role or pass in 
# the desired value under vars for each task. These variables will take precedence over the defaults.

- name: Dataguard
  hosts: localhost
  
  tasks:
    
    - include_vars: networking_ocids.yml

    - name: Create Remote Peering
      include_role:
        name: networking
        tasks_from: remote_peering.yml
      vars:
        compartment_id: "ocid1.compartment.oc1..aaaaaaaab3yw6vwv6zafelbx6zvhuszn5iaoesrwxkh6d645arl266w4aofq"
        primary_vcn_id: "{{ lookup('vars', tv1 + '_vcn_id') }}"
        primary_client_route_table_id: "{{ lookup('vars', tv1 + '_client_route_table_id') }}"
        primary_internet_gateway_id: "{{ lookup('vars', tv1 + '_internet_gateway_id') }}"
        
    
    # - name: Provision Standby Exadata 
    # TO DO!!

    # - name: Provision Standby Database
    # TO DO!!

    # "msg": "Internal error occurred"
    - name: Enable DataGuard
      include_role:
        name: database_creation
        tasks_from: dataguard.yml
      vars:
        region: "us-ashburn-1"
        primary_database_id: "ocid1.database.oc1.iad.abuwcljsnyyvi6mci4duwkgfkigiy2wxlfunmrlnf2575tp7qarkwmnl4lsq"
        standby_availability_domain: "rLid:US-PHOENIX-AD-1"
        standby_display_name: "DRDB2"
        standby_hostname: "drdb2"
        standby_subnet_id: "ocid1.subnet.oc1.phx.aaaaaaaaui7ivfa7fcuqzcjgy5k3rdzjd45h4xvyp5ksvvel3wuwluvfc5aa"
        shape: "VM.Standard2.4"


      
    