
# Playbook exacs_setup.yml creates an Exadata Cloud Service environment by calling the Exadata Infrastructure role and Exadata VM Cluster role

- name: 'ExaCS Set-Up'
  hosts: 'localhost'
    
  tasks:

    - include_vars: './vars/{{ vars_file }}'

    - name: 'Create Exadata Infrastructure for ExaCS'
      include_role:
        name: 'exacs_infra'
    
    - name: 'Create VM Cluster for ExaCS'
      include_role:
        name: 'exacs_vm_cluster'
  