
# Playbook exacc_setup.yml creates an Exadata Cloud at Customer environment by calling the Exadata VM Cluster role,
# Database Home role, and Database role. Assumes that the Exadata Infrastructure has already been provisioned by Oracle.

# Run this playbook with the following command in order to set the variables ssh_public_keys (for the vm_cluster creation)
# and db_admin_password (for the database creation):

#     ansible-playbook exacc_setup.yml --extra-vars 'db_admin_password=<db_admin_password> ssh_public_keys=<ssh_public_keys>'


- name: ExaCC Set-Up
  hosts: localhost
  
  tasks:

    - include_vars: './vars/{{ vars_file }}'
    
    # TO DO: What other steps for ExaCC set-up? VM Cluster Network? 
    
    # - name: Create VM Cluster for ExaCC
    #   include_role:
    #     name: exadata_vm_cluster
    
    - name: Create Database Home for ExaCC
      include_role:
        name: database_home
    
    - name: Create Database for ExaCC
      include_role:
        name: database
 
    # - name: Add Backup Destination for ExaCC
    #   include_role:
    #     name: database_backups
    