
# Playbook exacs_setup.yml creates an Exadata Cloud Service environment by calling the Exadata Infrastructure role and Exadata VM Cluster role

- name: 'ExaCS Set-Up'
  hosts: 'localhost'
    
  tasks:

    - include_vars:
        dir: './vars'
        files_matching: '{{ vars_file }}'

    - name: 'Create Networking for ExaCS'
      include_role:
        name: 'networking'

    - name: 'Create Exadata Infrastructure for ExaCS'
      include_role:
        name: 'exacs_infra'
    
    - name: 'Create VM Cluster for ExaCS'
      include_role:
        name: 'exacs_vm_cluster'
  