
- name: ExaCC Set-Up
  hosts: localhost
  vars:
      exadata_type: exacc
  
  tasks:
    
    - name: Validate Networking for ExaCC
      debug:
        msg: "TO DO!"

    # What other steps for ExaCC set-up? 

    # VM Cluster Network?

    - name: Create Exadata Infrastructure for ExaCC
      include_role:
        name: exadata
    
    - name: Create Database for ExaCC
      include_role:
        name: database   
      