
# Playbook exacc_setup.yml creates an Exadata Cloud at Customer environment by calling the Exadata VM Cluster role,
# Database Home role, and Database role. Assumes that the Exadata Infrastructure has already been provisioned by Oracle.

# To ensure you are creating your environment with the correct values, please check the defaults/main.yml file within each role or pass in 
# the desired value under vars for each task. These variables will take precedence over the defaults.

- name: ExaCC Set-Up
  hosts: localhost
  vars:
      exadata_type: exacc
  
  tasks:
    
    # TO DO: What other steps for ExaCC set-up? VM Cluster Network? 

    - name: Create VM Cluster for ExaCC
      include_role:
        name: exadata_vm_cluster
    
    - name: Create Database Home for ExaCC
      include_role:
        name: database_home_creation
      vars:
        vm_cluster_id: "ocid1.dbsystem.oc1.phx.abyhqljsocyxodibkxdqsnkx3z5gu2lvjczhseei6ju3knvmr3w2mi2yz56a" 
        compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" 
    
    - name: Create Database for ExaCC
      include_role:
        name: database_creation
      vars:
        compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" 
        # db_home_id: "ocid1.dbhome.oc1.phx.abyhqljsctnqkpksjxbiu7abdl2mujajupge7k3d2snk3whjczanpzjxjm6a"