
- name: ExaCC Set-Up
  hosts: localhost
  vars:
      exadata_type: exacc
  
  tasks:
    
    # What other steps for ExaCC set-up? VM Cluster Network? Don't need ExaCC Set-up command because will be already set-up by Oracle.

    - name: Create VM Cluster for ExaCC
      include_role:
        name: exadata_vm_cluster
    
    - name: Create Database Home for ExaCC
      include_role:
        name: database_home_creation
      vars:
        vm_cluster_id: "ocid1.dbsystem.oc1.phx.abyhqljsocyxodibkxdqsnkx3z5gu2lvjczhseei6ju3knvmr3w2mi2yz56a" 
        compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" 
    
    - name: Create Database for ExaCC
      include_role:
        name: database_creation
      vars:
        compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" 
        # db_home_id: "ocid1.dbhome.oc1.phx.abyhqljsctnqkpksjxbiu7abdl2mujajupge7k3d2snk3whjczanpzjxjm6a"