
# Playbook exacs_setup.yml creates an Exadata Cloud Service environment by calling the Exadata Infrastructure role, Exadata VM Cluster role,
# Database Home role, and Database role. 

# Run this playbook with the following command in order to set the variables ssh_public_keys (for the vm_cluster creation)
# and db_admin_password (for the database creation):

#     ansible-playbook exacs_setup.yml --extra-vars 'db_admin_password=<db_admin_password> ssh_public_keys=<ssh_public_keys>'


- name: ExaCS Set-Up
  hosts: localhost
    
  tasks:

    - include_vars: './vars/{{ vars_file }}'

    # - name: 'Create Networking for ExaCS'
    #   include_role:
    #     name: networking

    # - name: 'Create Exadata Infrastructure for ExaCS'
    #   include_role:
    #     name: exadata_infra
    
    # - name: 'Create VM Cluster for ExaCS'
    #   include_role:
    #     name: exadata_vm_cluster
    
    - name: 'Create Database Home for ExaCS'
      include_role:
        name: database_home
 
    - name: 'Create Database for ExaCS'
      include_role:
        name: database