
# Playbook exacc_setup.yml creates an Exadata Cloud at Customer environment by calling the Exadata VM Cluster role,
# Database Home role, and Database role. Assumes that the Exadata Infrastructure has already been provisioned by Oracle.

- name: 'ExaCC Set-Up'
  hosts: 'localhost'
  
  tasks:

    - include_vars:
        dir: './vars'
        files_matching: '{{ vars_file }}'
    
    - name: 'Create VM Cluster Network and VM Cluster for ExaCC'
      include_role:
        name: 'exacc_vm_cluster'
    
    