
- name: ExaCS Set-Up
  hosts: localhost
  collections:
    - oracle.oci
  vars:
      # compartment_id: "ocid1.compartment.oc1..aaaaaaaab3yw6vwv6zafelbx6zvhuszn5iaoesrwxkh6d645arl266w4aofq" #Tanvi
      compartment_id: "ocid1.compartment.oc1..aaaaaaaaukmxzkrg53zvf3d7bjpnzdrt2qb3snnjt7vdys4p3qalmzo3yfma" #ExaCS
      exadata_type: exacs
      db_home_id: ocid1.dbhome.oc1.phx.abyhqljsn4z6kk4a62b77ucvzh6bo3t5iygp7wpmhrtvkghcf2j6twebpkyq
  
  tasks:
    
    # - name: Create Networking for Exadata Cloud Service
    #   include_role:
    #     name: networking

    # - name: Create Exadata Infrastructure for Exadata Cloud Service
    #   include_role:
    #     name: exadata
    
    - name: Create Database for Exadata Cloud Service
      include_role:
        name: database
      vars:
        vm_cluster_id: "ocid1.dbsystem.oc1.phx.abyhqljsocyxodibkxdqsnkx3z5gu2lvjczhseei6ju3knvmr3w2mi2yz56a"    
      