
- name: Networking Set-Up
  hosts: localhost
  collections:
    - oracle.oci
  
  tasks:

    - name: Create Networking for Exadata Cloud Service
      include_role:
        name: networking
      vars:
        compartment_id: "ocid1.compartment.oc1..aaaaaaaab3yw6vwv6zafelbx6zvhuszn5iaoesrwxkh6d645arl266w4aofq"
      