
# Playbook networking_teardown.yml terminates a basic database network by calling the individual task networking_teardown from the networking role.
# Assumes that you used the networking role to set-up the environment.

- name: 'Networking teardown'
  hosts: 'localhost'
  
  tasks:

    - include_vars:
        dir: './vars'
        files_matching: '{{ vars_file }}'

    - name: 'Delete Networking Components'
      include_role:
        name: 'networking'
        tasks_from: 'networking_teardown.yml'
        
        
        
      
    