- hosts: "server"
  become: true
  become_user: oracle
  gather_facts: no
  
  tasks:
    
    - name: Create PDB
      include_role:
        name: pdb
      vars:
        oracle_home: '/u01/app/oracle/product/19.0.0.0/dbhome_1'
        oracle_sid: 'PR2'
        oracle_unique_name: 'PR2_iad1fh'
        