- name: 'Get a specific compartment'
  oci_identity_compartment_facts:
    tenancy_id: '{{ tenancy_id }}'
    auth_type: 'instance_principal'
    region: '{{ region }}'
    tenancy: '{{ tenancy_id }}'
  register: compartment_id_result
- debug:
    msg: '{{ compartment_id_result }}'