
# Check VM Cluster state

- name: 'Check Tenancy Connection'
  when: hostgroup == 'localhost'
  include_tasks: check_tenancy_connection.yml

- name: 'Check Var File'
  when: hostgroup == 'localhost'
  include_tasks: check_var_file.yml

- name: 'Check Inventory'
  when: hostgroup != 'localhost'
  include_tasks: check_inventory.yml    
    