
- name: 'create pdb'
  expect:
    command: 'dbaascli pdb create --pdbname {{ pdb_name }} --dbname {{ workload_tag }}{{ db_name }}'
    responses:
      \bpassword\b: '{{ pdb_password }}'
    echo: 'yes'
    timeout: '300'
  register: pdb_create_result
- debug:
    msg: '{{ pdb_create_result }}'