
- name: 'Discover Database {{ workload_tag }}{{ db_home_name }} Unique Name'
  when: db_unique_name is not defined
  delegate_to: localhost
  import_role:
    name: 'database'
    tasks_from: 'db_discovery.yml'
- assert: { that: db_unique_name is defined }

- name: 'Discover Oracle Home'
  when: oracle_home is not defined
  delegate_to: localhost
  import_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'
- assert: { that: oracle_home is defined }

- name: 'Create PDB Using DBCA Silent Mode'
  shell:  |
    dbca -silent -createPluggableDatabase -sourceDB {{ db_unique_name }} -pdbName {{ PDBname }} -pdbAdminUserName pdbadmin -pdbAdminPassword {{ pdb_admin_password }} -createUserTableSpace true -pdbStorageMAXSizeInMB 100000
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    PATH: '{{ ansible_env.PATH }}:{{ oracle_home }}/bin'
  register: pdb_creation_result
  failed_when: pdb_creation_result.stdout.find('100% complete') == -1
- debug:
    msg: '{{ pdb_creation_result }}'

- name: 'Create Set TDE for PDB sql'
  copy:
    dest: '/tmp/SetTDEforPDB.sql'
    content: |
      ALTER SESSION SET CONTAINER = {{ PDBname }};
      ADMINISTER KEY MANAGEMENT SET KEY FORCE KEYSTORE IDENTIFIED BY "{{ pdb_admin_password }}" WITH BACKUP;
      QUIT;
  become: 'true'
  become_user: oracle
  become_method: sudo
  register: create_tde_sql_result
- debug:
    msg: '{{ create_tde_sql_result }}'

- name: Set TDE Key for PDB
  shell: |
    {{ oracle_home }}/bin/sqlplus / as sysdba @/tmp/SetTDEforPDB.sql
  become: yes
  become_user: oracle
  become_method: sudo
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    ORACLE_SID: '{{ oracle_sid }}'
  register: set_tde_result
- debug:
    msg: '{{ set_tde_result }}'

# - name: 'Create temporary sql file'
#   ansible.builtin.tempfile:
#     state: 'file'
#     suffix: 'sql'
#   become: 'true'
#   become_user: 'oracle'
#   become_method: 'sudo'
#   register: 'sqltemp_file_result'
# - debug:
#     msg: '{{ sqltemp_file_result }}'
# - set_fact:
#     sqltemp_path: "{{ sqltemp_file_result.path }}"

# - name: 'Create Set TDE for PDB sql'
#   copy:
#     dest: '{{ sqltemp_path }}'
#     content: |
#       ALTER SESSION SET CONTAINER = {{ PDBname }};
#       ADMINISTER KEY MANAGEMENT SET KEY FORCE KEYSTORE IDENTIFIED BY "{{ pdb_admin_password }}" WITH BACKUP;
#       QUIT;
#   become: 'true'
#   become_user: oracle
#   become_method: sudo
#   register: create_tde_sql_result
# - debug:
#     msg: '{{ create_tde_sql_result }}'

# - name: Set TDE Key for PDB
#   shell: |
#     {{ oracle_home }}/bin/sqlplus / as sysdba @{{ sqltemp_path }}
#   become: yes
#   become_user: oracle
#   become_method: sudo
#   environment:
#     ORACLE_HOME: '{{ oracle_home }}'
#     ORACLE_SID: '{{ oracle_sid }}'
#   register: set_tde_result
# - debug:
#     msg: '{{ set_tde_result }}'


# DBCLI Method

# - name: 'create pdb'
#   expect:
#     command: 'dbaascli pdb create --pdbname {{ PDBname }} --dbname {{ workload_tag }}{{ CDBname }}'
#     responses:
#       \bpassword\b: '{{ pdb_admin_password }}'
#     echo: 'yes'
#     timeout: '300'
#   become: 'true'
#   become_user: 'oracle'
#   register: pdb_create_result
# - debug:
#     msg: '{{ pdb_create_result }}'


