- name: 'Discover Database {{ workload_tag }}{{ db_home_name }} Unique Name'
  when: db_unique_name is not defined
  delegate_to: localhost
  import_role:
    name: 'database'
    tasks_from: 'db_discovery.yml'
- assert: { that: db_unique_name is defined }

- name: 'Discover Oracle Home'
  when: oracle_home is not defined
  delegate_to: localhost
  import_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'
- assert: { that: oracle_home is defined }

- name: 'Delete PDB Using DBCA Silent Mode'
  shell:  |
    dbca -silent -deletePluggableDatabase -sourceDB {{ db_unique_name }} -pdbName {{ pdb_name }}
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    PATH: '{{ ansible_env.PATH }}:{{ oracle_home }}/bin'
  register: pdb_deletion_result
  failed_when: pdb_deletion_result.stdout.find('100% complete') == -1
- debug:
    msg: '{{ pdb_deletion_result }}'


# DBCLI Method

# - name: 'delete pdb'
#   shell:  |
#     dbaascli pdb delete --pdbname {{ pdb_name }} --dbname {{ workload_tag }}{{ db_name }}
#   become: 'true'
#   become_user: 'oracle'
#   register: pdb_delete_result
# - debug:
#     msg: '{{ pdb_delete_result }}'

# - name: PDB Info
#   include_tasks: pdb_info.yml