
- name: 'Create PDB Using DBCA Silent Mode'
  shell:  |
    dbca -silent -createPluggableDatabase -sourceDB {{ db_unique_name }} -pdbName {{ pdb_name }} -pdbAdminUserName pdbadmin -pdbAdminPassword {{ pdb_admin_password }} -createUserTableSpace true
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    PATH: '{{ ansible_env.PATH }}:{{ oracle_home }}/bin'
  register: pdb_creation_result
  failed_when: pdb_creation_result.stdout.find('100% complete') == -1
- debug:
    msg: '{{ pdb_creation_result }}'

- name: 'Create temporary sql file'
  ansible.builtin.tempfile:
    state: 'file'
    suffix: 'sql'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  register: 'sqltemp_file_result'
- debug:
    msg: '{{ sqltemp_file_result }}'
- set_fact:
    sqltemp_path: "{{ sqltemp_file_result.path }}"

- name: 'Create Set TDE for PDB sql'
  copy:
    dest: '{{ sqltemp_path }}'
    content: |
      ALTER SESSION SET CONTAINER = {{ pdb_name }};
      ADMINISTER KEY MANAGEMENT SET KEY FORCE KEYSTORE IDENTIFIED BY "{{ pdb_admin_password }}" WITH BACKUP;
      QUIT;
  become: 'true'
  become_user: oracle
  become_method: sudo
  register: create_tde_sql_result
- debug:
    msg: '{{ create_tde_sql_result }}'

- name: Set TDE Key for PDB
  shell: |
    {{ oracle_home }}/bin/sqlplus / as sysdba @{{ sqltemp_path }}
  become: yes
  become_user: oracle
  become_method: sudo
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    ORACLE_SID: '{{ oracle_sid }}'
  register: set_tde_result
- debug:
    msg: '{{ set_tde_result }}'


# DBCLI Method

# - name: 'create pdb'
#   expect:
#     command: 'dbaascli pdb create --pdbname {{ pdb_name }} --dbname {{ workload_tag }}{{ db_name }}'
#     responses:
#       \bpassword\b: '{{ pdb_admin_password }}'
#     echo: 'yes'
#     timeout: '300'
#   become: 'true'
#   become_user: 'oracle'
#   register: pdb_create_result
# - debug:
#     msg: '{{ pdb_create_result }}'


