# TO DO: TEST

- name: DB Home Discovery
  include_role:
    name: database_home_creation
    tasks_from: db_home_discovery.yml

- name: List DBs
  include_tasks: db_discovery.yml

- name: Delete database
  oci_database_database:
    region: "{{ region }}"
    database_id: "{{ database_id }}"
    state: absent
  when: database_id is defined