- block:
  - name: Delete database
    oci_database_database:
      region: region: "{{ region }}"
      database_id: "{{ database_id }}"
      state: absent
    register: result
  - debug:
      msg: "{{ result }}"