- block:
  - name: Delete database
    oci_database_database:
      region: "us-phoenix-1"
      database_id: "{{ database_id }}"
      state: "absent"
    register: result
  - debug:
      msg: "{{ result }}"