- block:
  - name: Check cloud_vm_cluster
    oci_database_cloud_vm_cluster:
      region: "us-phoenix-1"
      cloud_vm_cluster_id: "{{ vm_cluster_id }}"
    register: result
  - set_fact:
      vm_cluster_lifecycle_state: "{{ result.cloud_vm_cluster.lifecycle_state }}"
  when: exadata_type == "exacs"

- block:
  - name: Check vm_cluster
    oci_database_vm_cluster:
      region: "us-phoenix-1"
      vm_cluster_id: "{{ vm_cluster_id }}"
    register: result
  - set_fact:
      vm_cluster_lifecycle_state: "{{ result.vm_cluster.lifecycle_state }}"
  when: exadata_type == "exacc"

- debug:
    msg: "Cannot perform database operation, VM_Cluster is in {{ vm_cluster_lifecycle_state }} state."
  when: vm_cluster_lifecycle_state != "AVAILABLE"