
- name: Create Data Guard Association for VM Database
  oci_database_data_guard_association:
    database_id: '{{ primary_database_id }}'
    database_admin_password: '{{ db_admin_password }}'
    protection_mode: 'MAXIMUM_PERFORMANCE'
    transport_type: 'ASYNC'
    creation_type: 'NewDbSystem'
    availability_domain: '{{ standby_availability_domain }}'
    display_name: '{{ workload_tag }}{{ db_name }}'
    hostname: '{{ standby_hostname }}'
    subnet_id: '{{ standby_subnet_id }}'
    shape: '{{ shape }}'
  register: dataguard_create_result
- debug:
    msg: '{{ dataguard_create_result }}'

