
- name: 'Check for existing DB with name {{ workload_tag }}{{ db_name }}'
  include_tasks: db_discovery.yml
- name: 'Assert that database_id is not defined'
  assert: { that: database_id is not defined }

- name: 'Create database with name {{ workload_tag }}{{ db_name }}'
  oci_database_database:
    compartment_id: '{{ compartment_id }}'
    source: 'NONE'
    db_home_id: '{{ db_home_id }}'
    database:
      admin_password: '{{ db_admin_password }}'
      db_name: '{{ workload_tag }}{{ db_name }}'
  register: db_creation_result
- name: 'DB Creation Output'
  debug:
    msg: '{{ db_creation_result }}'
- set_fact:
    database_id: '{{ db_creation_result.database.id }}'