
- name: 'Assert that db_home_id is defined'
  assert: { that: db_home_id is defined }

# Source is NONE (default)

- name: 'Create {{ workload_tag }}{{ CDBname }} database'
  oci_database_database:
    compartment_id: '{{ compartment_id }}'
    database:
      admin_password: '{{ db_admin_password }}'
      character_set: '{{ character_set }}'
      database_software_image_id: '{{ database_software_image_id }}'
      db_backup_config: '{{ db_backup_config }}'
      CDBname: '{{ workload_tag }}{{ CDBname }}'
      db_workload: '{{ db_workload }}'
      defined_tags: '{{ db_defined_tags }}'
      freeform_tags: '{{ db_freeform_tags }}'
      ncharacter_set: '{{ ncharacter_set }}'
      PDBname: '{{ PDBname }}'
    db_home_id: '{{ db_home_id }}'
    db_version: '{{ db_version }}' 
    key_by: ['db_home_id', 'CDBname']
    kms_key_id: '{{ kms_key_id }}' 
    kms_key_version_id: '{{ kms_key_version_id }}' 
    source: '{{ db_source }}'
  register: 'db_creation_result'
- name: 'DB Creation Output'
  debug:
    msg: '{{ db_creation_result }}'
- set_fact:
    database_id: '{{ db_creation_result.database.id }}'