# TO DO: TEST

- name: DB Home Discovery
  include_role:
    name: database_home
    tasks_from: db_home_discovery.yml

- name: List DBs
  include_tasks: db_discovery.yml

- name: Delete database
  when: database_id is defined
  oci_database_database:
    database_id: '{{ database_id }}'
    state: absent
  