# TO DO: TEST

- name: List DBs
  when: database_id is not defined
  include_tasks: db_discovery.yml

- name: Delete database
  when: database_id is defined
  oci_database_database:
    database_id: '{{ database_id }}'
    state: absent
  