
- name: Discover DB Home for Database '{{ workload_tag }}{{ db_name }}'
  when: db_home_id is not defined
  include_role:
    name: database_home
    tasks_from: db_home_discovery.yml
- assert: { that: db_home_id is defined }

- name: Discover Database '{{ workload_tag }}{{ db_name }}'
  oci_database_database_facts:
    compartment_id: '{{ compartment_id }}'
    db_name: '{{ workload_tag }}{{ db_name }}'
    db_home_id: '{{ db_home_id }}'
  register: result
- debug:
    msg: '{{ result }}'
- set_fact: 
    database_id: '{{ result.databases[0].id}}'
  when: result.databases|length > 0 