
- name: 'Discover Database {{ workload_tag }}{{ db_home_name }} Unique Name'
  when: db_unique_name is not defined
  delegate_to: localhost
  import_role:
    name: 'database'
    tasks_from: 'db_discovery.yml'
- assert: { that: db_unique_name is defined }

- name: 'Discover Oracle Home'
  when: oracle_home is not defined
  delegate_to: localhost
  import_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'
- assert: { that: oracle_home is defined }

- name: 'Copy Script to Host'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  copy:
    src: 'sample_script'
    dest: '/home/oracle/'
  register: 'copy_script_result'
- debug:
    msg: '{{ copy_script_result }}'

- name: Change file ownership, group and permissions
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  ansible.builtin.file:
    path: /home/oracle/sample_script
    mode: '0770'

- name: 'Execute Script'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell: |
    ./sample_script
  args:
    chdir: /home/oracle/
  register: script_execution_result
- debug:
    msg: "{{ script_execution_result }}"


# - name: 'Execute SQL Script'
#   shell: echo exit |
#     $ORACLE_HOME/bin/sqlplus -s / as sysdba @/home/oracle/sample_script.sql
#   environment:
#     ORACLE_HOME: '{{ oracle_home }}'
#     ORACLE_SID: '{{ oracle_sid }}'
#     ORACLE_UNIQUE_NAME: '{{ db_unique_name }}'
#   register: result
# - debug:
#     msg: "{{ result }}"