
- name: 'Discover DB Home for Database {{ workload_tag }}{{ db_name }}'
  when: db_home_id is not defined
  include_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'

# Create Database

# - name: 'Create Database'
#   include_tasks: 'db_create_database.yml'   

- name: 'Execute Set-Up Script'
  include_tasks: 'execute_script.yml'   

 
    