

- name: Check VM Cluster Lifecycle State
  include_tasks: check_vm.yml

- name: Create DB Home and Database
  include_tasks: db_creation.yml
  when: vm_cluster_lifecycle_state == "AVAILABLE"

- name: DB Backups
  include_tasks: db_backup.yml
  vars:
    backup_name: "AnsibleTest"
    
    