
- name: 'Discover DB Home for Database {{ workload_tag }}{{ CDBname }}'
  when: db_home_id is not defined
  include_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'

# Create Database

- name: 'Create Database'
  include_tasks: 'db_create_database.yml'

 
    