
# Delete ExaCC VM Cluster

- name: Delete vm cluster
  oci_database_vm_cluster:
    vm_cluster_id: '{{ vm_cluster_id }}'
    state: absent
  register: vm_cluster_delete_result
- debug:
    msg: '{{ vm_cluster_delete_result }}'
