
# Create ExaCC VM Cluster

- name: 'Check Exadata Infrastructure variable.'
  assert:
    that:
      - exadata_infrastructure_id is defined
    fail_msg: 'exadata_infrastructure_id value not defined. Please run create_exacc.yml and pass in ExaCC OCID.'

- name: Create vm cluster
  oci_database_vm_cluster:
    key_by: ['exadata_infrastructure_id', 'display_name']
    display_name: '{{ vm_cluster_name }}'
    compartment_id: '{{ compartment_id }}'
    exadata_infrastructure_id: '{{ exadata_infrastructure_id }}'
    vm_cluster_network_id: '{{ vm_cluster_network_id }}'
    cpu_core_count: '{{ cpu_core_count }}'
    memory_size_in_gbs: '{{ memory_size_in_gbs }}'
    db_node_storage_size_in_gbs: '{{ db_node_storage_size_in_gbs }}'
    data_storage_size_in_tbs: '{{ data_storage_size_in_tbs }}'
    ssh_public_keys: '{{ ssh_public_keys }}'
    license_model: '{{ license_model }}'
    is_sparse_diskgroup_enabled: '{{ is_sparse_diskgroup_enabled }}'
    is_local_backup_enabled: '{{ is_local_backup_enabled }}'
    time_zone: '{{ time_zone }}'
    gi_version: '{{ gi_version }}'
  register: vm_cluster_create_result
- debug:
    msg: '{{ vm_cluster_create_result }}'
- set_fact:
    vm_cluster_id: '{{ vm_cluster_create_result.vm_cluster.id }}'