# db_home
db_home_name: 'home1'
db_version: '19.0.0.0'

# database
db_name: 'DB1'
auto_backup_enabled: 'false'      # true or false. If false, cannot define auto_backup_window. 
auto_backup_window: 'SLOT_TWO'
# recovery_window_in_days: '30'

# pdb
pdb_name: 'TstPDB'