
- block: # when backup_destination_type == 'NFS'

  - name: List backup_destinations of type NFS
    oci_database_backup_destination_facts:
      compartment_id: '{{ compartment_id }}'
      display_name: '{{ workload_tag }}NFS'
      type: '{{ backup_destination_type }}'  
    register: result
  - debug:
      msg: '{{ result }}'
  - set_fact: 
      backup_destination_id: '{{ result.backup_destinations[0].id}}'
    when: result.backup_destinations|length > 0 
  
  when: backup_destination_type is defined and backup_destination_type == 'NFS'


- block: # when backup_destination_type == 'RECOVERY_APPLICANCE'

  - name: List backup_destinations of type Recovery Appliance
    oci_database_backup_destination_facts:
      compartment_id: '{{ compartment_id }}'
      display_name: '{{ workload_tag }}RA'
      type: '{{ backup_destination_type }}'  
    register: result
  - debug:
      msg: '{{ result }}'
  - set_fact: 
      backup_destination_id: '{{ result.backup_destinations[0].id}}'
    when: result.backup_destinations|length > 0 
  
  when: backup_destination_type is defined and backup_destination_type == 'RECOVERY_APPLICANCE'