# NOT TESTED

- block:
  
  - name: Create db_backup_destination
    oci_database_backup_destination:
      region: "us-phoenix-1"
      compartment_id: "{{ compartment_id }}"
      display_name: display_name_example
      type: " {{ db_backup_destination_type }}"
      connection_string: connection_string_example
    when: db_backup_destination_type == "RECOVERY_APPLICANCE"
  
  when: exadata_type == "exacc"