# TO DO: TEST 

- name: 'Check Exadata Infrastructure is defined and type exacs.'
  assert: { that: exadata_type is defined and exadata_type == 'exacs' }

- name: Database Discovery
  when: database_id is not defined
  include_role:
    name: database
    tasks_from: db_discovery.yml
- assert: { that: database_id is defined }

- name: Create new database backup
  oci_database_backup:
    database_id: '{{ database_id }}'
    display_name: '{{ workload_tag }}Bkup'
  register: result
- debug:
    msg: '{{ result }}'