# TO DO: TEST 

- block:      # exadata type is exacc
  - assert: {that: backup_destination_id is defined and backup_destination_type is defined}
  - name: Enable automatic database backups
    oci_database_database:
      database_id: '{{ database_id }}'
      db_backup_config:
        auto_backup_enabled: '{{ auto_backup_enabled }}'
        auto_backup_window: '{{ auto_backup_window }}'
        recovery_window_in_days: '{{ recovery_window_in_days }}'
        backup_destination_details:
        - id: '{{ backup_destination_id }}'
          type: '{{ backup_destination_type }}'
    register: result
  when: exadata_type is defined and exadata_type == 'exacc'

- name: Enable automatic database backups for ExaCS
  when: exadata_type is defined and exadata_type == 'exacs'
  oci_database_database:
    database_id: '{{ database_id }}'
    db_backup_config:
      auto_backup_enabled: '{{ auto_backup_enabled }}'
      auto_backup_window: '{{ auto_backup_window }}'
      recovery_window_in_days: '{{ recovery_window_in_days }}'
  register: result
  
- debug:
    msg: '{{ result }}'