- name: 'Check Database backup variables are defined.'
  assert:
    that:
      - auto_backup_enabled is defined
    fail_msg: 'Check to make sure variable auto_backup_enabled is defined.'

- name: 'Get OCID for {{ workload_tag }}{{ db_name }} DB'
  when: database_id is not defined
  include_role:
    name: 'database'
    tasks_from: 'db_discovery.yml'
- assert: { that: database_id is defined }

- name: 'Set automatic database backups'
  oci_database_database:
    database_id: '{{ database_id }}'
    db_backup_config:
      auto_backup_enabled: '{{ auto_backup_enabled }}'
      # auto_backup_window: '{{ auto_backup_window }}'
      # recovery_window_in_days: '{{ recovery_window_in_days }}'
  register: 'auto_backup_result'
- debug:
    msg: '{{ auto_backup_result }}'

