- name: Check Exadata Infrastructure variable.
  assert:
    that:
      - exadata_type is defined
      - exadata_type == 'exacc' or exadata_type == 'exacs'

# ExaCC Backups

- name: Create Backup Destination
  when: >
    (exadata_type == 'exacc') and
    (backup_destination_type is defined) and 
    (backup_destination_type == 'RECOVERY_APPLIANCE' or backup_destination_type == 'NFS') and
    (backup_destination_id is not defined)
  include_tasks: db_create_backup_destination.yml

- name: Add Backup Destination to Database
  when: exadata_type == 'exacc'
  include_tasks: db_add_backup_destination.yml

# ExaCS Backups

- name: Create new backup
  when: exadata_type == 'exacs'
  include_tasks: db_backup_standalone.yml


# Automatic Backups

- name: Enable automatic backups
  when: auto_backup_enabled is defined and auto_backup_enabled == 'true'
  include_tasks: db_enable_automatic_backup.yml
  


  