- name: 'Discover ExaCS for VM Cluster {{ workload_tag }}{{ vm_cluster_name }}'
  when: exadata_infrastructure_id is not defined
  include_role:
    name: 'exacs_infra'
    tasks_from: 'exacs_discovery.yml'
- name: 'Assert that exadata_infrastructure_id is defined'
  assert: { that: exadata_infrastructure_id is defined }

- name: ExaCS VM Cluster Discovery
  oci_database_cloud_vm_cluster_facts:
    compartment_id: '{{ compartment_id }}'
    display_name: '{{ workload_tag }}{{ vm_cluster_name }}'
    cloud_exadata_infrastructure_id: '{{ exadata_infrastructure_id }}'
  register: vm_cluster_discovery_result
- debug:
    msg: '{{ vm_cluster_discovery_result }}'
- set_fact: 
    vm_cluster_id: '{{ vm_cluster_discovery_result.cloud_vm_clusters[0].id }}'
    vm_cluster_lifecycle_state: '{{ vm_cluster_discovery_result.cloud_vm_clusters[0].lifecycle_state }}'
  when: vm_cluster_discovery_result.cloud_vm_clusters|length == 1

