# Create ExaCS VM Cluster

- name: 'Check Exadata Infrastructure variable.'
  assert:
    that:
      - exadata_infrastructure_id is defined
    fail_msg: 'exadata_infrastructure_id value not defined. Please run create_exacc.yml and pass in ExaCC OCID.'

- name: Create cloud vm cluster
  oci_database_cloud_vm_cluster:
    key_by: ['cloud_exadata_infrastructure_id', 'display_name']
    compartment_id: '{{ compartment_id }}'
    subnet_id: '{{ client_subnet_id }}'
    backup_subnet_id: '{{ backup_subnet_id }}'
    cloud_exadata_infrastructure_id: '{{ exadata_infrastructure_id }}'
    cpu_core_count: '{{ vm_cluster_cpu_count }}'
    display_name: '{{ workload tag }}{{ vm_cluster_display_name }}'
    hostname: '{{ vm_cluster_hostname }}'
    ssh_public_keys: '{{ ssh_public_keys }}'
    gi_version: '{{ gi_version }}'
  register: vm_cluster_create_result
- debug:
    msg: '{{ vm_cluster_create_result }}'
- set_fact:
    vm_cluster_id: '{{ vm_cluster_create_result.cloud_vm_cluster.id }}'