# Create ExaCS VM Cluster

- name: 'Discover ExaCS for VM Cluster {{ workload_tag }}{{ vm_cluster_name }}'
  when: exadata_infrastructure_id is not defined
  include_role:
    name: 'exacs_infra'
    tasks_from: 'exacs_discovery.yml'
- name: 'Assert that exadata_infrastructure_id is defined'
  assert: { that: exadata_infrastructure_id is defined }

- name: 'Networking is defined'
  assert: { that: backup_subnet_id is defined and subnet_id is defined }

- name: Create cloud vm cluster
  oci_database_cloud_vm_cluster:
    backup_network_nsg_ids: '{{ vm_cluster_backup_network_nsg_ids }}'
    backup_subnet_id: '{{ backup_subnet_id }}'
    cloud_exadata_infrastructure_id: '{{ exadata_infrastructure_id }}'
    # cluster_name: '{{ cluster_name }}'
    compartment_id: '{{ compartment_id }}'
    compute_nodes: '{{ vm_cluster_compute_nodes }}'
    cpu_core_count: '{{ vm_cluster_cpu_count }}'
    data_storage_percentage: '{{ vm_cluster_data_storage_percentage }}'
    defined_tags: '{{ vm_cluster_defined_tags }}'
    display_name: '{{ workload tag }}{{ vm_cluster_display_name }}'
    domain_name: '{{ vm_cluster_domain_name }}'
    freeform_tags: '{{ vm_cluster_freeform_tags }}'
    gi_version: '{{ vm_cluster_gi_version }}'
    hostname: '{{ vm_cluster_hostname }}'
    is_local_backup_enabled: '{{ is_local_backup_enabled }}'
    is_sparse_diskgroup_enabled: '{{ is_sparse_diskgroup_enabled }}'
    key_by: ['cloud_exadata_infrastructure_id', 'display_name']
    license_model: '{{ license_model }}'
    nsg_ids: '{{ vm_cluster_nsg_ids }}'
    ssh_public_keys: '{{ vm_cluster_ssh_public_keys }}'
    storage_size_in_gbs: '{{ vm_cluster_storage_size_in_gbs }}'
    time_zone: '{{ vm_cluster_time_zone }}'
    subnet_id: '{{ client_subnet_id }}'
  register: vm_cluster_create_result
- debug:
    msg: '{{ vm_cluster_create_result }}'
- set_fact:
    vm_cluster_id: '{{ vm_cluster_create_result.cloud_vm_cluster.id }}'