
# Set-Up Exadata Infrastructure

- name: 'Check Exadata Type variable.'
  assert:
    that:
      - exadata_type is defined and exadata_type == 'exacs'
    fail_msg: 'Define variable exadata_type to be exacs.'

- name: Create ExaCS VM Cluster
  include_tasks: exacs_create_vm_cluster.yml
  
    