
- name: Check for DB Home
  include_tasks: db_home_discovery.yml

- assert: { that: db_home_id is not defined }

- name: Create db home
  oci_database_db_home:
    region: "{{ region }}"
    compartment_id: "{{ compartment_id }}"
    source: VM_CLUSTER_NEW
    vm_cluster_id: "{{ vm_cluster_id }}"
    display_name: "{{ workload_prefix }}{{ db_home_name }}"
    db_version: "{{ db_version }}"
  register: result
- debug:
    msg: "{{ result }}"
- set_fact:
    db_home_id: "{{ result.db_home.id }}"