- name: List db_homes
  oci_database_db_home_facts:
    compartment_id: '{{ compartment_id }}'
    display_name: '{{ workload_prefix }}{{ db_home_name }}'
  register: result
- debug:
    msg: '{{ result }}'
- set_fact: 
    db_home_id: '{{ result.db_homes[0].id}}'
  when: result.db_homes|length > 0 